'use client';

import { useState, useEffect } from 'react';
import Image from 'next/image';
import { Download, Link as LinkIcon, AlertCircle, FileVideo, FileAudio, FileImage, Youtube, Facebook, Twitter, Instagram, Smartphone, ArrowRight } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

type MediaType = 'video' | 'audio' | 'image';
type Platform = 'youtube' | 'facebook' | 'twitter' | 'instagram' | 'tiktok' | 'unknown';

interface DownloadOption {
  format: string;
  quality: string;
  size: string;
  type: MediaType;
}

const initialOptions: DownloadOption[] = [
  { format: 'MP4', quality: '1080p', size: '145 MB', type: 'video' },
  { format: 'MP4', quality: '720p', size: '65 MB', type: 'video' },
  { format: 'MP3', quality: '320kbps', size: '8 MB', type: 'audio' },
  { format: 'JPG', quality: 'Original', size: '2 MB', type: 'image' },
];

export function Downloader() {
  const [url, setUrl] = useState('');
  const [options, setOptions] = useState<DownloadOption[]>(initialOptions);
  
  const [showCustomForm, setShowCustomForm] = useState(false);
  const [customFormat, setCustomFormat] = useState('');
  const [customQuality, setCustomQuality] = useState('');
  const [customError, setCustomError] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [resultReady, setResultReady] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const [activeDownload, setActiveDownload] = useState<{
    id: string;
    option: DownloadOption;
    progress: number;
    speed: string;
    eta: string;
  } | null>(null);

  const [pendingDownload, setPendingDownload] = useState<DownloadOption | null>(null);
  const [adCountdown, setAdCountdown] = useState(4);

  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (pendingDownload && adCountdown > 0) {
      timer = setTimeout(() => {
        setAdCountdown(prev => prev - 1);
      }, 1000);
    }
    return () => clearTimeout(timer);
  }, [pendingDownload, adCountdown]);

  const initiateDownloadWithAd = (opt: DownloadOption) => {
    setPendingDownload(opt);
    setAdCountdown(4);
  };

  const skipAdAndDownload = () => {
    if (pendingDownload) {
       handleStartDownload(pendingDownload);
       setPendingDownload(null);
    }
  };

  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (activeDownload && activeDownload.progress < 100) {
      interval = setInterval(() => {
        setActiveDownload(prev => {
          if (!prev) return prev;
          const nextProgress = Math.min(100, prev.progress + Math.random() * 5 + 2);
          
          let nextSpeed = prev.speed;
          let nextEta = prev.eta;
          
          if (nextProgress < 100) {
             nextSpeed = (3 + Math.random() * 5).toFixed(1) + ' MB/s';
             const remainingSeconds = Math.max(1, Math.floor((100 - nextProgress) / 3));
             nextEta = remainingSeconds > 60 
               ? `00:${Math.floor(remainingSeconds/60).toString().padStart(2, '0')}:${(remainingSeconds%60).toString().padStart(2, '0')}`
               : `00:00:${remainingSeconds.toString().padStart(2, '0')}`;
          } else {
             nextSpeed = '0 MB/s';
             nextEta = 'Complete';
          }

          return {
            ...prev,
            progress: nextProgress,
            speed: nextSpeed,
            eta: nextEta
          };
        });
      }, 500);
    }
    return () => clearInterval(interval);
  }, [activeDownload]);

  const detectPlatform = (input: string): Platform => {
    if (input.includes('youtube.com') || input.includes('youtu.be')) return 'youtube';
    if (input.includes('facebook.com') || input.includes('fb.watch')) return 'facebook';
    if (input.includes('twitter.com') || input.includes('x.com')) return 'twitter';
    if (input.includes('instagram.com')) return 'instagram';
    if (input.includes('tiktok.com')) return 'tiktok';
    return 'unknown';
  };

  const currentPlatform = url ? detectPlatform(url) : 'unknown';

  // Trigger a simulated file download when complete
  useEffect(() => {
    if (activeDownload && activeDownload.progress >= 100 && activeDownload.eta === 'Complete') {
      const timer = setTimeout(() => {
        try {
          const element = document.createElement("a");
          const file = new Blob([`Generated by OmniSave. Simulated media content for ${currentPlatform}.\nQuality: ${activeDownload.option.quality}`], {type: 'text/plain'});
          element.href = URL.createObjectURL(file);
          element.download = `omnisave_video_${Date.now()}.${activeDownload.option.format.toLowerCase()}`;
          element.style.display = "none";
          document.body.appendChild(element);
          element.click();
          document.body.removeChild(element);
          setActiveDownload(prev => prev ? { ...prev, eta: 'Downloaded' } : null);
        } catch (err) {
          console.error("Failed to simulate download", err);
        }
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [activeDownload, currentPlatform]);

  const handleStartDownload = (opt: DownloadOption) => {
    setActiveDownload({
       id: Math.random().toString(),
       option: opt,
       progress: 0,
       speed: 'Connecting...',
       eta: 'Calculating...'
    });
  };

  const getPlatformIcon = (platform: Platform) => {
    switch (platform) {
      case 'youtube': return <Youtube className="w-6 h-6 text-red-600" />;
      case 'facebook': return <Facebook className="w-6 h-6 text-blue-600" />;
      case 'twitter': return <Twitter className="w-6 h-6 text-blue-400" />;
      case 'instagram': return <Instagram className="w-6 h-6 text-pink-600" />;
      case 'tiktok': return <Smartphone className="w-6 h-6 text-black" />;
      default: return <LinkIcon className="w-6 h-6 text-gray-400" />;
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!url.trim()) {
      setError('Please paste a valid video or image URL first.');
      return;
    }
    
    try {
      new URL(url.trim().startsWith('http') ? url.trim() : `https://${url.trim()}`);
    } catch (e) {
      setError('That URL doesnt look quite right. Try copying it again.');
      return;
    }
    
    setError(null);
    setResultReady(false);
    setIsProcessing(true);
    setActiveDownload(null); // Clear previous download progress

    // Mock API call
    setTimeout(() => {
      setIsProcessing(false);
      setResultReady(true);
    }, 2000);
  };

  const handleAddCustom = () => {
    if (!/^[a-zA-Z0-9]+$/.test(customFormat) || customFormat.length < 2 || customFormat.length > 10) {
      setCustomError('Format must be 2-10 alphanumeric letters.');
      return;
    }
    if (customQuality.trim().length < 2 || customQuality.trim().length > 20) {
      setCustomError('Quality must be between 2 and 20 characters.');
      return;
    }
    setOptions(prev => [...prev, {
      format: customFormat.toUpperCase(),
      quality: customQuality.trim(),
      size: 'Unknown',
      type: 'video'
    }]);
    setCustomFormat('');
    setCustomQuality('');
    setShowCustomForm(false);
    setCustomError('');
  };

  return (
    <div className="w-full max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="bg-slate-900 rounded-[2rem] shadow-xl shadow-black/50 overflow-hidden border border-slate-800">
        
        {/* Enhanced Advertisement Section */}
        <div className="relative group overflow-hidden bg-slate-900 border-b border-slate-800 p-1 block w-full">
          <div className="absolute top-2 left-2 z-10 bg-slate-950/80 backdrop-blur border border-slate-800 text-[9px] text-slate-400 px-2 py-0.5 rounded uppercase tracking-widest font-bold">Sponsored</div>
          <div className="flex flex-col sm:flex-row items-center justify-between p-4 px-6 pt-8 pb-6 sm:p-6 sm:pt-6 bg-gradient-to-r from-slate-800 to-indigo-900/20 rounded-xl rounded-t-2xl sm:rounded-b-none border border-slate-700/50 hover:border-indigo-500/30 transition-colors">
            <div className="flex flex-col sm:flex-row items-center sm:items-start gap-4 text-center sm:text-left mb-4 sm:mb-0">
              <div className="w-12 h-12 bg-indigo-500/20 rounded-xl flex items-center justify-center border border-indigo-500/30 shrink-0 shadow-inner">
                <span className="text-2xl">🛡️</span>
              </div>
              <div>
                <h4 className="text-white font-bold text-sm sm:text-base mb-1">Protect your online privacy today</h4>
                <p className="text-xs text-slate-400 max-w-md line-clamp-2">Get military-grade encryption and access geo-blocked content with blazing fast speeds. Try it risk-free.</p>
              </div>
            </div>
            <button className="w-full sm:w-auto shrink-0 bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs px-6 py-2.5 rounded-lg transition-all shadow-lg shadow-indigo-600/20 uppercase tracking-wide">
              Learn More
            </button>
          </div>
        </div>

        <div className="p-6 sm:p-10 flex flex-col justify-center gap-4">
          <div className="text-center mb-8">
            <h2 className="text-3xl font-bold text-white leading-tight sm:text-4xl mb-4">
              Download content from <br/><span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400">any social platform.</span>
            </h2>
            <p className="text-sm text-slate-400 max-w-2xl mx-auto">
              Paste a link from YouTube, Facebook, Twitter, Instagram, TikTok, or thousands of other sites to save video and audio in high quality.
            </p>
          </div>

          <form onSubmit={handleSubmit} className="relative max-w-3xl mx-auto w-full">
            <div className="relative flex items-center">
              <div className="absolute left-4 p-2 bg-slate-900 rounded-lg">
                {getPlatformIcon(currentPlatform)}
              </div>
              <input
                type="text"
                placeholder="Paste URL here (Instagram, YouTube, TikTok...)"
                value={url}
                onChange={(e) => {
                   setUrl(e.target.value);
                   setError(null);
                   setResultReady(false);
                }}
                className="w-full pl-16 pr-32 py-4 rounded-xl border border-slate-700 bg-slate-950 text-slate-300 focus:border-indigo-500 focus:outline-none transition-all shadow-inner"
              />
              <button
                type="submit"
                disabled={isProcessing}
                className="absolute right-2 top-2 bottom-2 px-6 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-lg transition-all shadow-lg shadow-indigo-600/20 flex items-center gap-2 disabled:bg-indigo-900 disabled:text-slate-400"
              >
                {isProcessing ? (
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
                  >
                    <Download className="w-5 h-5" />
                  </motion.div>
                ) : (
                   <>
                     <span>Fetch Media</span>
                   </>
                )}
              </button>
            </div>
            
            <AnimatePresence>
              {error && (
                <motion.div 
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="absolute mt-2 text-red-400 flex items-center gap-1 text-xs font-medium"
                >
                  <AlertCircle className="w-4 h-4" />
                  {error}
                </motion.div>
              )}
            </AnimatePresence>
          </form>

          {/* Results Area */}
          <AnimatePresence>
            {resultReady && (
              <motion.div 
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                exit={{ opacity: 0, height: 0 }}
                className="mt-8 overflow-hidden"
              >
                <div className="bg-slate-950 rounded-2xl p-6 border border-slate-800">
                  <div className="flex flex-col md:flex-row gap-8">
                    {/* Thumbnail Mock */}
                    <div className="w-full md:w-1/3 aspect-video bg-slate-800 rounded-xl overflow-hidden relative group border border-slate-700">
                      {/* Using picsum for a mock thumbnail */}
                      <Image 
                        src="https://picsum.photos/seed/omni/800/450" 
                        alt="Video Thumbnail" 
                        fill
                        className="object-cover group-hover:scale-105 transition-transform duration-500 opacity-80"
                        referrerPolicy="no-referrer"
                      />
                      <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                         <div className="bg-indigo-600 p-3 rounded-full shadow-lg">
                           <Download className="w-5 h-5 text-white" />
                         </div>
                      </div>
                    </div>

                    <div className="w-full md:w-2/3 flex flex-col justify-center">
                      <h3 className="text-xl font-bold text-white mb-1 truncate" title="Amazing Video Pulled from the Web">
                        Amazing Content Pulled from {currentPlatform !== 'unknown' ? currentPlatform : 'the Web'}
                      </h3>
                      <p className="text-xs text-slate-500 mb-6">Duration: 12:34 • Source: {url.substring(0, 40)}...</p>
                      
                      <div className="space-y-3">
                        <div className="flex items-center justify-between mt-2">
                           <h4 className="text-[10px] font-bold tracking-widest text-slate-500 uppercase">Available Downloads</h4>
                           <button 
                             onClick={() => setShowCustomForm(!showCustomForm)}
                             className="text-[10px] font-bold tracking-widest text-indigo-400 hover:text-indigo-300 uppercase transition-colors"
                           >
                             {showCustomForm ? 'Cancel Custom' : 'Add Custom'}
                           </button>
                        </div>
                        
                        <AnimatePresence>
                          {showCustomForm && (
                            <motion.div
                              initial={{ opacity: 0, height: 0 }}
                              animate={{ opacity: 1, height: 'auto' }}
                              exit={{ opacity: 0, height: 0 }}
                              className="overflow-hidden"
                            >
                              <div className="p-3 mb-3 bg-slate-900 border border-slate-700 rounded-xl space-y-3">
                                <div className="grid grid-cols-2 gap-3">
                                  <div>
                                    <label className="block text-[10px] uppercase font-bold text-slate-500 mb-1">Format (e.g. MKV)</label>
                                    <input 
                                      type="text" 
                                      value={customFormat}
                                      onChange={(e) => setCustomFormat(e.target.value)}
                                      className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-sm text-slate-300 focus:outline-none focus:border-indigo-500" 
                                    />
                                  </div>
                                  <div>
                                    <label className="block text-[10px] uppercase font-bold text-slate-500 mb-1">Quality (e.g. 1440p)</label>
                                    <input 
                                      type="text" 
                                      value={customQuality}
                                      onChange={(e) => setCustomQuality(e.target.value)}
                                      className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2 text-sm text-slate-300 focus:outline-none focus:border-indigo-500" 
                                    />
                                  </div>
                                </div>
                                {customError && <p className="text-xs text-red-400 font-medium">{customError}</p>}
                                <button
                                  onClick={handleAddCustom}
                                  className="w-full bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold text-xs py-2 rounded-lg transition-colors border border-slate-700"
                                >
                                  Save Output Format
                                </button>
                              </div>
                            </motion.div>
                          )}
                        </AnimatePresence>

                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                           {options.map((opt, i) => (
                             <button 
                               key={i}
                               className="flex items-center justify-between p-3 rounded-xl border border-slate-700 bg-slate-800/50 hover:bg-indigo-900/30 hover:border-indigo-500/50 transition-colors group"
                               onClick={() => initiateDownloadWithAd(opt)}
                             >
                               <div className="flex items-center gap-3">
                                 <div className={`p-2 rounded-lg border border-slate-700 ${opt.type === 'video' ? 'bg-indigo-900/40 text-indigo-400' : opt.type === 'audio' ? 'bg-purple-900/40 text-purple-400' : 'bg-emerald-900/40 text-emerald-400'}`}>
                                    {opt.type === 'video' && <FileVideo className="w-4 h-4" />}
                                    {opt.type === 'audio' && <FileAudio className="w-4 h-4" />}
                                    {opt.type === 'image' && <FileImage className="w-4 h-4" />}
                                 </div>
                                 <div className="text-left">
                                   <div className="font-bold text-slate-200 text-sm">{opt.quality}</div>
                                   <div className="text-[10px] text-slate-500">{opt.format} • {opt.size}</div>
                                 </div>
                               </div>
                               <Download className="w-5 h-5 text-slate-500 group-hover:text-indigo-400 transition-colors" />
                             </button>
                           ))}
                        </div>

                        {/* Active Download Progress */}
                        <AnimatePresence>
                          {activeDownload && (
                            <motion.div
                              initial={{ opacity: 0, scale: 0.95, height: 0, marginTop: 0 }}
                              animate={{ opacity: 1, scale: 1, height: 'auto', marginTop: 24 }}
                              exit={{ opacity: 0, scale: 0.95, height: 0, marginTop: 0 }}
                              className="p-4 rounded-xl border border-indigo-500/30 bg-indigo-900/20 overflow-hidden"
                            >
                               <div className="flex justify-between items-end mb-3">
                                  <div>
                                    <div className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest mb-1">Downloading {activeDownload.option.quality}</div>
                                    <div className="font-mono text-sm text-slate-300">{activeDownload.progress >= 100 ? '100%' : `${Math.floor(activeDownload.progress)}%`} • {activeDownload.speed}</div>
                                  </div>
                                  <div className="text-right">
                                    <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1">Time Left</div>
                                    <div className="font-mono text-sm text-slate-300">{activeDownload.eta}</div>
                                  </div>
                               </div>
                               
                               <div className="w-full h-1.5 bg-slate-800/80 rounded-full overflow-hidden shadow-inner relative">
                                  <motion.div 
                                    className="absolute left-0 top-0 bottom-0 bg-gradient-to-r from-indigo-500 to-purple-400"
                                    initial={{ width: 0 }}
                                    animate={{ width: `${activeDownload.progress}%` }}
                                    transition={{ ease: "linear", duration: 0.5 }}
                                  />
                               </div>
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </div>
                    </div>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
          
        </div>
      </div>

      {/* Ad Overlay Modal */}
      <AnimatePresence>
        {pendingDownload && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm"
          >
             <div className="bg-slate-900 border border-slate-800 w-full max-w-xl rounded-[2rem] overflow-hidden shadow-2xl flex flex-col relative top-0 scale-100">
                <div className="p-4 bg-slate-950 flex justify-between items-center border-b border-slate-800">
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Advertisement</span>
                  {adCountdown > 0 ? (
                    <span className="text-slate-400 text-xs font-bold bg-slate-800 px-4 py-2 rounded-full border border-slate-700">Skip in <span className="text-white">{adCountdown}s</span></span>
                  ) : (
                    <button 
                      onClick={skipAdAndDownload}
                      className="text-white text-xs font-bold bg-indigo-600 hover:bg-indigo-500 px-5 py-2 rounded-full transition-colors flex items-center gap-2 shadow-lg shadow-indigo-500/20"
                    >
                      Skip Ad <ArrowRight className="w-4 h-4" />
                    </button>
                  )}
                </div>
                <div className="p-12 h-72 flex flex-col items-center justify-center bg-slate-800 relative group cursor-pointer" onClick={() => window.open('https://example.com', '_blank')}>
                   <div className="w-16 h-16 bg-slate-700 rounded-full mb-4 flex items-center justify-center border border-slate-600 shadow-inner">
                      <span className="text-2xl">🚀</span>
                   </div>
                   <span className="text-white text-xl font-black mb-2">OmniSave Premium</span>
                   <p className="text-slate-400 text-center max-w-sm text-sm">Get unlimited downloads, zero ads, and ultra-fast speeds. Upgrade today and save 50%!</p>
                </div>
             </div>
          </motion.div>
        )}
      </AnimatePresence>

    </div>
  );
}
